name: Build ruleset

on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: write
  checks: write
  pull-requests: read

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run compile
      - name: commit compiled ruleset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "automation@leaflink.com"
          git config user.name "LeafLink Automation"
          git checkout origin ${{ github.head_ref }}
          git add ./frosting-ruleset.compiled.yaml
          git commit -m "Automated: Updating compiled ruleset"
          git push
