name: Build ruleset

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"
      - run: npm ci
      - run: npm run compile-ci
      - name: commit compiled ruleset
        env:
          GITHUB_TOKEN: ${{ secrets.LEAFLINK_AUTOMATION_PAT }}
        run: |
          git config user.email "github-automation@leaflink.com"
          git config user.name "leaflink-automation"
          git fetch
          git checkout ${{ github.head_ref }}
          git pull
          git add ./dist/frosting-ruleset.compiled.yaml
          git commit -m "Automated: Updating compiled ruleset"
          git push
